export const songs = [
  { title: 'Dearly Beloved', src: '/Assets/khsongs/1-01 Dearly Beloved.mp3', cover: '/Assets/khpics/kh2-twilight-town-station-of-serenity.jpg' },
  { title: 'Dive into the Heart', src: '/Assets/khsongs/1-04 Dive into the Heart -Destati-.mp3', cover: '/Assets/khpics/kh-dive-to-the-heart.jpg' },
  { title: 'Hand To Hand', src: '/Assets/khsongs/1-05 Hand To Hand.mp3', cover: '/Assets/khpics/3d-sora-riku-traverse-town.png' },
  { title: 'Kairi I', src: '/Assets/khsongs/1-10 Kairi I.mp3', cover: '/Assets/khpics/KH3 Re Mind Key Art.png' },
  { title: 'It Began with a Letter', src: '/Assets/khsongs/1-11 It Began with a Letter.mp3', cover: '/Assets/khpics/kh-sora.jpg' },
  { title: 'Le Sanctuarie', src: '/Assets/khsongs/1-11 Le Sanctuaire.mp3', cover: '/Assets/khpics/3d-la-cite-des-cloches-nave.png' },
  { title: 'Night of Fate', src: '/Assets/khsongs/1-13 Night of Fate.mp3', cover: '/Assets/khpics/kh-box-art.jpg' },
  { title: 'Traverse Town', src: '/Assets/khsongs/1-16 Traverse Town.mp3', cover: '/Assets/khpics/3d-traverse-town-fountain-plaza.png' },
  { title: 'To Our Surprise', src: '/Assets/khsongs/1-22 To Our Surprise.mp3', cover: '/Assets/khpics/kh-wonderland-bizarre-room-2.jpg' },
  { title: 'The Fun Fair', src: '/Assets/khsongs/2-07 The Fun Fair.mp3', cover: '/Assets/khpics/3d-pranksters-paradise-circus.png' },
  { title: 'An Adventure in Atlantica', src: '/Assets/khsongs/2-08 An Adventure in Atlantica.mp3', cover: '/Assets/khpics/kh-atlantica-undersea-valley.jpg' },
  { title: 'This is Halloween', src: '/Assets/khsongs/2-12 This is Halloween.mp3', cover: '/Assets/khpics/kh-halloween-town-graveyard.jpg' },
  { title: 'One For All', src: '/Assets/khsongs/2-14 One For All.mp3', cover: '/Assets/khpics/3d-country-of-the-musketeers-theatre.png' },
  { title: 'Pirates Gigue', src: '/Assets/khsongs/2-16 Pirates Gigue.mp3', cover: '/Assets/khpics/kh-neverland-deck.jpg' },
  { title: 'Blast Away -Gummi Ship III-', src: '/Assets/khsongs/2-19 Gummi Ship III.mp3', cover: '/Assets/khpics/hd-sora-donald-goofy-chair.jpg' },
  { title: 'Hollow Bastion', src: '/Assets/khsongs/2-20 Hollow Bastion.mp3', cover: '/Assets/khpics/kh-hollow-bastion1.jpg' },
  { title: 'Deep Drop', src: '/Assets/khsongs/2-21 Deep Drop.mp3', cover: '/Assets/khpics/3d-dream.png' },
  { title: 'Scherzo Di Notte', src: '/Assets/khsongs/2-21 Scherzo Di Notte.mp3', cover: '/Assets/khpics/kh-hollow-bastion-great-crest.jpg' },
  { title: 'Fragments of Sorrow', src: '/Assets/khsongs/2-27 Fragments of Sorrow.mp3', cover: '/Assets/khpics/kh-hollow-bastion.jpg' },
  { title: 'L Oscurità dell Ignot', src: '/Assets/khsongs/3-01 LOscurità dellIgnot.mp3', cover: '/Assets/khpics/3d-drop.png' },
  { title: 'Lord of the Castle', src: '/Assets/khsongs/3-07 Lord of the Castle.mp3', cover: '/Assets/khpics/com-box-art.jpg' },
  { title: 'Musique pour la tristesse de Xion', src: '/Assets/khsongs/3-09 Musique pour la tristesse de Xion.mp3', cover: '/Assets/khpics/days-box-art.jpg' },
  { title: 'Risky Romp', src: '/Assets/khsongs/1-11 Risky Romp.mp3', cover: '/Assets/khpics/bbs-dwarf-woodlands-cottage-clearing.jpg' },
  { title: 'Vector to the Heavens', src: '/Assets/khsongs/3-11 Vector to the Heavens.mp3', cover: '/Assets/khpics/days-roxas-falling.jpg' },
  { title: 'Another Side -Battle Version-', src: '/Assets/khsongs/3-12 Another Side -Battle Ver.-.mp3', cover: '/Assets/khpics/recom-box-art.jpg' },
  { title: 'Sinister Sundown', src: '/Assets/khsongs/4-05 Sinister Sundown.mp3', cover: '/Assets/khpics/kh2fm-twilight.jpg' },
  { title: 'Tension Rising', src: '/Assets/khsongs/4-09 Tension Rising.mp3', cover: '/Assets/khpics/kh2fm-sora-roxas-station-tower.jpg' },
  { title: 'The 13th Struggle', src: '/Assets/khsongs/4-12 The 13th Struggle.mp3', cover: '/Assets/khpics/coded-box-art.jpg' },
  { title: 'Rowdy Rumble', src: '/Assets/khsongs/5-22 Rowdy Rumble.mp3', cover: '/Assets/khpics/bbs-e3-promotional-art.jpg' },
  { title: 'Castle Escapade', src: '/Assets/khsongs/1-15 Castle Escapade.mp3', cover: '/Assets/khpics/bbs-castle-of-dreams-forest.jpg' },
  { title: 'Sinister Shadows', src: '/Assets/khsongs/6-29 Sinister Shadows.mp3', cover: '/Assets/khpics/kh2-box-art.jpg' },
];
